### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by Koshub** [facebook/flux#309]
npm@2.14.12
```
 npm install
npm WARN package.json react-boilerplate@0.2.0 No repository field.
npm WARN package.json react-boilerplate@0.2.0 license should be a valid SPDX license expression
npm WARN peerDependencies The peer dependency envify@~0.2.0 included from stylesheets will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN deprecated react-tools@0.8.0: react-tools is deprecated. For more information, visit https://fb.me/react-tools-deprecated
npm WARN peerDependencies The peer dependency envify@~0.2.0 included from react will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> fsevents@0.2.1 install /Users/.../react-boilerplate/node_modules/jsxc/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'ThrowException' in
      namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:343:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::Error, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:348:9: error: no type named 'ThrowException' in
      namespace 'v8'
    v8::ThrowException(error);
    ~~~~^
../node_modules/nan/nan.h:355:53: error: no member named 'New' in 'v8::String';
      did you mean 'v8::TypeSwitch::New'?
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                    ^~~~~~~~~~~~~~~
                                                    v8::TypeSwitch::New
/Users/.../.node-gyp/4.2.4/include/node/v8.h:4705:28: note: 
      'v8::TypeSwitch::New' declared here
  static Local<TypeSwitch> New(Local<FunctionTemplate> type);
                           ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:355:69: error: calling a private constructor of class
      'v8::Local<v8::FunctionTemplate>'
    v8::Local<v8::Value> err = v8::Exception::Error(v8::String::New(msg));
                                                                    ^
/Users/.../.node-gyp/4.2.4/include/node/v8.h:326:13: note: declared private
      here
  V8_INLINE Local(S* that)
            ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:357:65: error: too few arguments to function call,
      expected 2, have 1
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
                                      ~~~~~~~~~~~~~~            ^
/Users/.../.node-gyp/4.2.4/include/node/v8.h:2499:3: note: 'New' declared
      here
  static Local<Integer> New(Isolate* isolate, int32_t value);
  ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:357:26: error: no member named 'New' in 'v8::String'
    obj->Set(v8::String::New("code"), v8::Int32::New(errorNumber));
             ~~~~~~~~~~~~^
../node_modules/nan/nan.h:369:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::TypeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:373:5: error: no member named 'ThrowException' in
      namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:373:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::TypeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:377:12: error: no member named 'New' in 'v8::String'
    return _NAN_ERROR(v8::Exception::RangeError, errmsg);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:381:5: error: no member named 'ThrowException' in
      namespace 'v8'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:11: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
      ~~~~^
../node_modules/nan/nan.h:381:5: error: no member named 'New' in 'v8::String'
    _NAN_THROW_ERROR(v8::Exception::RangeError, errmsg);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:324:26: note: expanded from macro '_NAN_THROW_ERROR'
      v8::ThrowException(_NAN_ERROR(fun, errmsg));                             \
                         ^~~~~~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:319:50: note: expanded from macro '_NAN_ERROR'
# define _NAN_ERROR(fun, errmsg) fun(v8::String::New(errmsg))
                                     ~~~~~~~~~~~~^
../node_modules/nan/nan.h:406:13: error: no member named 'smalloc' in namespace
      'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:141:71: note: expanded from macro 'NAN_INLINE'
# define NAN_INLINE(declarator) inline __attribute__((always_inline)) declarator
                                                                      ^
../node_modules/nan/nan.h:416:12: error: no matching function for call to 'New'
    return node::Buffer::New(data, size);
           ^~~~~~~~~~~~~~~~~
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:28:40: note: candidate
      function not viable: no known conversion from 'char *' to 'v8::Isolate *'
      for 1st argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:31:40: note: candidate
      function not viable: no known conversion from 'char *' to 'v8::Isolate *'
      for 1st argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:43:40: note: candidate
      function not viable: requires 3 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:36:40: note: candidate
      function not viable: requires 5 arguments, but 2 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:420:12: error: no matching function for call to 'New'
    return node::Buffer::New(size);
           ^~~~~~~~~~~~~~~~~
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:28:40: note: candidate
      function not viable: requires 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:31:40: note: candidate
      function not viable: requires at least 2 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:43:40: note: candidate
      function not viable: requires 3 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/.../.node-gyp/4.2.4/include/node/node_buffer.h:36:40: note: candidate
      function not viable: requires 5 arguments, but 1 was provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../fsevents.cc:6:
../node_modules/nan/nan.h:427:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(data, size);
           ~~~~~~~~~~~~~~^
../node_modules/nan/nan.h:727:49: error: too few arguments to function call,
      single argument 'isolate' was not specified
    v8::Local<v8::Object> obj = v8::Object::New();
                                ~~~~~~~~~~~~~~~ ^
/Users/.../.node-gyp/4.2.4/include/node/v8.h:2933:3: note: 'New' declared
      here
  static Local<Object> New(Isolate* isolate);
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/.../Development/Projects/goworkspace/src/flux-todomvc/react-boilerplate/node_modules/jsxc/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.2.1
react@0.8.0 node_modules/react

envify@0.2.0 node_modules/envify
├── through@2.3.8
└── falafel@0.2.1 (esprima@1.1.0-dev)

stylesheets@0.0.5 node_modules/stylesheets

statics-stylesheets@0.0.1 node_modules/statics-stylesheets
├── mimetype@0.0.5
├── fs-extra@0.8.1 (jsonfile@1.1.1, rimraf@2.2.8, ncp@0.4.2, mkdirp@0.3.5)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
└── rework@0.19.0 (hsb2rgb@1.0.2, rework-visit@1.0.0, rework-inherit@0.2.1, mime@1.2.11, color-parser@0.1.0, commander@1.0.4, debug@2.2.0, css@1.4.4)

jsxc@0.1.6 node_modules/jsxc
├── mkdirp@0.3.5
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── chokidar@0.8.4 (recursive-readdir@0.0.2)
└── react-tools@0.8.0 (esprima-fb@2001.1001.0-dev-harmony-fb, jstransform@2.0.3, commoner@0.8.15)

jest-cli@0.8.2 node_modules/jest-cli
├── object-assign@4.0.1
├── graceful-fs@4.1.2
├── diff@2.2.1
├── json-stable-stringify@1.0.0 (jsonify@0.0.0)
├── chalk@1.1.1 (escape-string-regexp@1.0.4, ansi-styles@2.1.0, supports-color@2.0.0, has-ansi@2.0.0, strip-ansi@3.0.0)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── which@1.2.1 (is-absolute@0.1.7)
├── worker-farm@1.3.1 (xtend@4.0.1, errno@0.1.4)
├── resolve@1.1.6
├── sane@1.3.0 (watch@0.10.0, minimist@1.2.0, exec-sh@0.2.0, minimatch@0.2.14, fb-watchman@1.6.0, walker@1.0.7)
├── cover@0.2.9 (which@1.0.9, underscore@1.2.4, underscore.string@2.0.0, cli-table@0.0.2)
├── node-haste@1.2.8 (esprima-fb@4001.1001.0-dev-harmony-fb)
├── jsdom@7.2.2 (webidl-conversions@2.0.1, acorn-globals@1.0.9, abab@1.0.2, sax@1.1.4, xml-name-validator@2.0.1, tough-cookie@2.2.1, symbol-tree@3.1.4, nwmatcher@1.3.7, cssom@0.3.0, whatwg-url-compat@0.6.5, parse5@1.5.1, acorn@2.7.0, escodegen@1.8.0, request@2.67.0, cssstyle@0.2.30)
└── istanbul@0.3.22 (abbrev@1.0.7, async@1.5.1, wordwrap@1.0.0, nopt@3.0.6, esprima@2.5.0, supports-color@3.1.2, once@1.3.3, fileset@0.2.1, escodegen@1.7.1, handlebars@4.0.5, js-yaml@3.4.6)
```

**Comment by zpao** [comment]
Closing, this is the same as #282 which I reopened.
