### ISSUE TITLE
npm install get error. ENOENT: no such file or directory, lstat '/Users/bokeadmin/project/flux/Flux.js'

### ISSUE THREAD

**Issue by zhouzhongyuan** [facebook/flux#359]
I only clone the repo, then run 'npm install', finally I got the error below.

How can I fix it ?

```bash  
[16:50:50] Starting 'dist:utils:min'...
fs.js:976
return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/Users/bokeadmin/project/flux/Flux.js'
    at Error (native)
    at Object.fs.lstatSync (fs.js:976:18)
    at DestroyableTransform.TransformStream [as _transform] (/Users/bokeadmin/project/flux/node_modules/gulp-header/index.js:38:12)
    at DestroyableTransform.Transform._read (/Users/bokeadmin/project/flux/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/bokeadmin/project/flux/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/bokeadmin/project/flux/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:313:64)
    at writeOrBuffer (/Users/bokeadmin/project/flux/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (/Users/bokeadmin/project/flux/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:241:11)
    at Stream.ondata (stream.js:31:26)
    at emitOne (events.js:96:13)
```
```bash
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.2.2/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! flux@3.0.0 prepublish: `gulp publish`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flux@3.0.0 prepublish script 'gulp publish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

```

**Comment by kyldvs** [comment]
Thanks for the report, this repros for me too. Will look into it

**Comment by zpao** [comment]
This is probably because of gulp-header. We had to lock the version to
1.8.2 in Draft to avoid an issue as well.

**Comment by kyldvs** [comment]
Perfect, that worked. Fixed with: https://github.com/facebook/flux/commit/0329be84e02b9cb4bf343c75edc02dc523270181

**Comment by kyldvs** [comment]
And here is the underlying issue it seems: https://github.com/tracker1/gulp-header/issues/36
