### ISSUE TITLE
React flux

### ISSUE THREAD

**Issue by AkramDots** [facebook/flux#394]
npm server is not running for this project .I have used following commands:
C:\Users\admin\Desktop\flux-master>npm start

> flux@3.1.2 start C:\Users\admin\Desktop\flux-master
> node index.js 

but server is not starting.
thanks

**Comment by kyldvs** [comment]
There is no start command: https://github.com/facebook/flux/blob/master/package.json#L24-L26

I'm not sure what you would expect it to do either.

**Comment by AkramDots** [comment]
I have not found this  module
Error: Cannot find module 'react-page-middleware'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\Desktop\flux-master\website\server\ser
ver.js:11:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by kyldvs** [comment]
Like I said there isn't a start command, running `npm start` shouldn't do anything. Whether it throws an error or not doesn't matter because there is no behavior defined that it should be trying to start.

If there is something you're trying to accomplish, first read through the readme and examples: https://github.com/facebook/flux/blob/master/README.md

Then if you are still having a problem open up an issue with clear details about what you are trying to do, what you expect to happen, and what is actually happening.

**Comment by AkramDots** [comment]
I want to run website using following link

https://github.com/facebook/flux/blob/master/website/README.md
